### ISSUE TITLE
kubify up None type not interable

### ISSUE THREAD

**Issue by philiptolk** [willyguggenheim/kubify#85]
# But Why?
inside .devcontainer in branch python

root@docker-desktop:/src/kubify# make pip && kubify up && cd services/backoffice/example-node-svc && kubify start

Successfully installed kubify
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.12) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
02-10-2022 05:28:17 : INFO : log : setup_logger : 43
                : (Process Details : (3519, MainProcess), 
                Thread Details : (281473770684432, MainThread))
Log 
                : start logging
💻💻💻💻💻💻💻💻💻💻💻💻💻💻💻💻💻💻💻💻💻👩‍💻💻💻💻💻💻💻💻💻💻💻💻💻💻💻💻💻💻💻💻💻💻💻💻💻💻
...................😎 Installing or Re-Installing Kubify 😎...................
💻💻💻💻💻💻💻💻💻💻💻💻💻💻💻💻💻💻💻💻💻💻💻💻💻💻💻💻💻💻💻💻💻💻💻💻💻💻💻💻💻💻💻💻💻💻💻
Traceback (most recent call last):
  File "/usr/local/bin/kubify", line 11, in <module>
    load_entry_point('kubify', 'console_scripts', 'kubify')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/src/kubify/kubify/cli.py", line 52, in <module>
    kubify.up()
  File "/src/kubify/kubify/src/kubify.py", line 73, in up
    kubify_up_class.up()
  File "/src/kubify/kubify/up.py", line 60, in up
    cluster.create()
  File "/usr/local/lib/python3.8/dist-packages/pytest_kind/cluster.py", line 129, in create
    config = pykube.KubeConfig.from_file(self.kubeconfig_path)
  File "/usr/local/lib/python3.8/dist-packages/pykube/config.py", line 98, in from_file
    self = cls(doc, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pykube/config.py", line 139, in __init__
    elif "current-context" in doc and doc["current-context"]:
TypeError: argument of type 'NoneType' is not iterable
root@docker-desktop:/src/kubify#

**Comment by willyguggenheim** [comment]
Fixed, Thank You For Testing!
